---
- name: Install nginx
  shell: sudo yum install epel-release -y

- name: Install nginx
  shell: sudo yum install nginx -y
  notify: nginx restart

- name: copy index.html file
  copy: src=index.html dest=/usr/share/nginx/html/
  notify: nginx restart
