- name: Installing Java
  shell : yum install java-11-openjdk-devel -y

- name: adding repo
  shell: sudo wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

- name: adding key
  shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install jenkins server
  shell: yum install jenkins -y
  notify: Restart jenkins
